import type { Service } from "./types";

// Static fallback used when the backend API is unreachable.
// Mirrors seed-data/services.csv (active services only).
export const FALLBACK_SERVICES: Service[] = [
  {
    id: 1,
    serviceName: "Signature Haircut",
    description:
      "Consultation, wash and precision cut by a senior specialist.",
    durationMinutes: 60,
    price: 1800,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 2,
    serviceName: "Global Hair Color",
    description: "Single-tone permanent color using L'Oréal Inoa.",
    durationMinutes: 120,
    price: 4500,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 3,
    serviceName: "Balayage Highlights",
    description: "Hand-painted highlights for a sun-kissed finish.",
    durationMinutes: 180,
    price: 7500,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 4,
    serviceName: "Keratin Smoothing",
    description: "Frizz-control treatment lasting up to four months.",
    durationMinutes: 210,
    price: 9500,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 5,
    serviceName: "Hair Spa Ritual",
    description: "Deep-conditioning scalp and hair therapy.",
    durationMinutes: 75,
    price: 2200,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 6,
    serviceName: "Beard Sculpt",
    description: "Hot-towel shave and beard shaping.",
    durationMinutes: 45,
    price: 900,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 7,
    serviceName: "Classic Manicure",
    description: "Nail care with cuticle work and polish.",
    durationMinutes: 45,
    price: 1200,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 8,
    serviceName: "Gel Pedicure",
    description: "Pedicure finished with long-lasting gel polish.",
    durationMinutes: 75,
    price: 2000,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 9,
    serviceName: "Hydrafacial Glow",
    description: "Three-step facial for instant radiance.",
    durationMinutes: 60,
    price: 3500,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 10,
    serviceName: "Bridal Makeup",
    description: "Full bridal look with airbrush makeup and hair.",
    durationMinutes: 240,
    price: 25000,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
  {
    id: 11,
    serviceName: "Threading & Waxing",
    description: "Eyebrow threading combined with full-arm wax.",
    durationMinutes: 40,
    price: 800,
    isActive: true,
    createdAt: "2026-01-01T09:00:00Z",
  },
];
